baseURL: "https://adilsarsenov.dev/"
languageCode: en-us
title: ASR Engineering

theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: posts
      name: Recent
      url: /posts
      weight: 20
    - identifier: archives
      name: Archive
      url: /archives
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 40
    - identifier: tags
      name: Tags
      url: /tags
      weight: 50

params:
  # theme
  showToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  math:
    enable: true
  highlight: true
  katex: true

  # for enhanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Adil Sarsenov"
    subtitle: "ML Engineer<br>Specializing in Computer Vision and MLOps"

    imageUrl: "home/casual.jpg"
    imageWidth: 220
    imageHeight: 220
    buttons:
       - name: Resume
         url: "https://drive.google.com/file/d/1FfTVfs3AcyIpPvapUCNgd43uz9QlsJH_/view?usp=sharing"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: true
    hiddenInSingle: false

  socialIcons:
    - name: "email"
      url: "mailto:research@adilsarsenov.dev"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/adil-sarsenov/"
    - name: "github"
      url: "https://github.com/bootleg-dev"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
    highlight:
      style: "pygments"